baseurl:
permalink: pretty
title: 'RHIME'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 6

collections:
  projects:
    output: true
    sort_by: weight
  scholars:
    output: true
  speakers:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"
  - scope:
      path: ""
      type: "scholars"
    values:
      layout: "scholars"
  - scope:
      path: ""
      type: "speakers"
    values:
      layout: "speakers"
sass:
  style: compressed # possible values: nested expanded compact compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

enable_project_categories: true
